# Se creara los contenedores a utilizar para este trabajo, teniendo el balanceador de carga y un contenedor por cada puerto de la pagina  
version: '3'
services:
  nginx_load_balancer: #Balanceador de cargas
    image: nginx
    volumes:
      - './nginx/default.conf:/etc/nginx/nginx.conf' #Accedera a los datos del nginx para coordinar las cargas
    ports:
      - '8080:80'
  # Cada APPID nos permitira asignar los puertos para cada pagina
  app1:
    image: node-app
    environment: 
      - APPID=1111
  app2:
    image: node-app
    environment: 
      - APPID=2222
  app3:
    image: node-app
    environment: 
      - APPID=3333
  app4:
    image: node-app
    environment: 
      - APPID=4444
  app5:
    image: node-app
    environment: 
      - APPID=5555
