version: '3'
services:
  nginx_load_balancer:
    image: nginx
    volumes:
      - './nginx/default.conf:/etc/nginx/nginx.conf'
    ports:
      - '8080:80'
  app1:
    image: node-app
    environment: 
      - APPID=1111
  app2:
    image: node-app
    environment: 
      - APPID=2222
  app3:
    image: node-app
    environment: 
      - APPID=3333
  app4:
    image: node-app
    environment: 
      - APPID=4444
  app5:
    image: node-app
    environment: 
      - APPID=5555
  mongodb:  #Se asigna nombre del contenedor, de la base de datos MongoDB
    image: mongo  #Se especifica la imagen a construir, para la BD de MongoDB
    ports:  #Se enlista los puertos a exponer/habilitar del contenedor, "PuertoAnfitrion:PuertoContenedor"
      - "27017:27017"
    environment:  #Se configura las variables de entorno necesarias al contenedor, de acuerdo a la imagen utilizada
      - MONGO_INITDB_ROOT_USERNAME=efra
      - MONGO_INITDB_ROOT_PASSWORD=password